
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: 📥 Install dependencies
        run: npm install

      - name: 🏗️ Build
        run: npm run build-only

      - name: 🚀Deploy to GitHub Pages🚀  // --> this deploys to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
